node:
  ip: 47.99.219.219
  password: guitqil123A
disk partition:
  primary: /dev/sdb4
  secondary: /dev/sdb5
basic operation:
  lvname: lvtest
  vgsize: 100G
  lvsize: 10G
thin vol:
  thinpoolsize: 100G
  thinvolsize: 10g
  poolextendsize: 10G
  volextendsize: 2G
  volreducesize: 5G
strip vol:
  stripvolsize: 10G
  stripnumbers: 2
  stripsize: 64
mirror vol:
  mirrorvolsize: 100G
  datavol: /dev/sdb4
  replicavol: /dev/sdb5
